apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto-app
  template:
    metadata:
      labels:
        app: crypto-app
    spec:
      containers:
        - name: crypto-app
          image: abhishek786/cypto-x:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: crypto-app
spec:
  type: NodePort
  selector:
    app: crypto-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000